######################################################################
# Automatically generated by qmake (3.1) Sun May 5 10:10:03 2019
######################################################################

TEMPLATE = app
TARGET = QtLudo
INCLUDEPATH += . ./include
QT += widgets core
CONFIG += debug

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
#DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
RESOURCES += res/resources.qrc
FORMS += about.ui \
    ueber_uns.ui \
    willkomme.ui

HEADERS += \
    include/SpielSpeichern.h \
    include/SpielWindow.h \
include/Path.h \
    include/Spiel.h \
    include/SpielScreen.h \
    include/SpielerFarbe.h \
    include/Spielfeld.h \
    include/Spielfigur.h \
    include/UeberUns.h \
include/ValueError.h \
    include/Wuerfel.h \
    include/ZeichnungPosition.h

SOURCES += Main.cpp \
Path.cpp ValueError.cpp \
    Spiel.cpp \
    SpielScreen.cpp \
    SpielSpeichern.cpp \
    SpielWindow.cpp \
    Spielfeld.cpp \
    Spielfigur.cpp \
    UeberUns.cpp \
    Wuerfel.cpp \
    ZeichnungPosition.cpp
